# Generated by Django 3.0.2 on 2020-01-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='static/events/images')),
                ('price', models.CharField(default='Free', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='static/events/images')),
                ('menu', models.ManyToManyField(blank=True, to='product.food')),
            ],
        ),
    ]
